export default {
  winner: 'Winner',
  label: 'Label',
  player1: 'Player 1',
  player2: 'Player 2',
  round: 'Round {0}',
  total: 'Total',
  restart: 'Restart',
  investment: 'Investment',
  clickToStart: 'Click to start expedition',
  score: 'Score: {0}',
  done: 'Done',
  lostCities: 'Lost Cities',
  player1Score: 'Player 1 score',
  player2Score: 'Player 2 score',
  activePlayer: 'Active player',
};
